#!/bin/sh

if test -r "$HOME/.Xresources"
then
    xrdb -merge "$HOME/.Xresources"
fi

if test -d /etc/X11/xinit/xinitrc.d
then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh
    do
        test -x "$f" && . "$f"
    done
fi

test -f "$HOME/.Xmodmap" && xmodmap "$HOME/.Xmodmap"

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

xset -b
xset s 300

xbindkeys
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
dunst &
copyq &

nm-applet &
blueman-applet &
ibus-daemon -drx
flameshot &

exec openbox-session
