#!/bin/sh

if test -r "$HOME/.Xresources"
then
	xrdb -merge "$HOME/.Xresources"
fi

if test -d /etc/X11/xinit/xinitrc.d
then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh
	do
		test -x "$f" && . "$f"
	done
fi

xset -b

xbindkeys
redshift -P -O 4000
ibus-daemon -drx
dunst &
xss-lock -- lock &
exec openbox-session
