#!/bin/bash
# Backup files and directories specified in list to ~/backup

set -e -o pipefail

list=(
	"$(xdg-user-dir DESKTOP)"
	"$(xdg-user-dir DOCUMENTS)"
	~/vg
)

for x in "${list[@]}"
do
	[[ -r "$x" ]] || exit 1
done

mkdir -p ~/backup
rsync -avz --delete "$@" "${list[@]}" ~/backup
