#!/usr/bin/env bash

ln -sf /usr/share/zoneinfo/UTC /etc/localtime
hwclock --systohc

sed -i '/#en_US.UTF-8 UTF-8/s/#//' /etc/locale.gen
sed -i '/#ja_JP.UTF-8 UTF-8/s/#//' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' >/etc/locale.conf

echo 'sakura' >/etc/hostname
cat <<EOF >/etc/hosts
127.0.0.1	localhost
::1		localhost
127.0.0.1	sakura.localdomain	sakura
EOF
pacman -S networkmanager
systemctl enable NetworkManager.service

passwd

pacman -S grub efibootmgr intel-ucode
grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
